name: monmate
description: High-Frequency Web3 Chess on Monad.
version: 1.0.0+1

environment:
  sdk: '^3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^0.12.0


  # Blockchain interaction
  web3dart: ^2.7.3
  walletconnect_flutter_v2: ^2.4.1

  # Networking & Storage
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Offline DB
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0

  # Presence, Social & Real-time
  supabase_flutter: ^2.4.0
  livekit_client: ^2.1.5

  # UI & Utilities
  animate_do: ^3.3.4
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
